### PR TITLE
add checkbox for publish/unpublish lecture

### PR DESCRIPTION
**Pull request by aleksandar-spasojevic**
Hi @tduong992 

I have started with the implementation of the publish/unpublish lecture checkbox in Edit Mode. So far I was able to add the component. 
Since I have not created a separate React Component for this checkbox, it is not needed to pass the checkbox value to a parent Component  `LecturePageTutorView`.
Let me know if that is ok with you, not creating a separate component?

### CODE REVIEW

**Comment by tduong992** [comment]
Looks good 👍🏻😊 
Oh, yeah that s fine! What I really meant is to pass the updated object to the ```LecturePage``` parent component, where - when the user clicks on 'save' - it will trigger a request to store the updated subject to the DB. So something similar to the ```LecturePageTutorView.onLectureTitleChange()``` calling ```this.props.onLectureTitleUpdate()```, which is defined in the ```LecturePage``` parent component. Sorry for the confusion ^^'

**Comment by wumacH** [comment]
added functionality to unpublish excercise materials, default: not published, other materials (like videos and lecture materials) has the attribut at database level as well, but is always set to true

ready for review & merge :-)

**Comment by aleksandar-spasojevic** [comment]
@wumacH thanks 👍

**Comment by tduong992** [comment]
Alright, reviewed, added a visible label to show the TUTOR (from lecture view mode) if the exercise file is published/unpublished, and added the functionality to publish/unpublish a lecture directly from the "actions" dropdown menu as well!

Available tests pass! Great job, thank you both! Let's merge this 😊

**Pull request merged**
