### PR TITLE
added user role functionality

### PR DESCRIPTION
**Pull request by wumacH**
- see example UploadComponent
- see github for more documentation how to use it

### CODE REVIEW

**Comment by wumacH** [comment]
see example UploadComponent:
as suggested here https://redux.js.org/recipes/writing-tests i export the component twice, once with the connect function and once only the component, otherwise the tests don't work because it's looking for the redux store, which is not available inside the unit test ...

do you have other ideas how to solve this problem? or is that a good solution so that we can apply it on every component?

**Comment by wumacH** [comment]
please take a look on the action: "loadUser", i think this reducer was the reason for the "loading bar"-error in some of our browsers (mine & Martin). This action is called in App.js and sets the "isLoading" parameter in the store to true, which forces to show the loading bar (take a look on the return of the App.js). The action stores the last path of a user, if he needs to login. Maybe we need to rename the function. On my browser i can now load the login page without a change of the "wait" param in the in18n.js file (maybe this parameter only forced sometimes to refresh the page). Additionaly, during "login" i can shortly see the loading-bar (which was probably the intention of this loading-bar).

Could someone check this?

**Comment by tduong992** [comment]
I've merged develop into this feature branch and fix the merge conflicts.. but it seems there is still a console error, not sure what is causing this from this branch :/
needs more debugging ^^'

**Comment by waedi** [comment]
> 
> 
> I've merged develop into this feature branch and fix the merge conflicts.. but it seems there is still a console error, not sure what is causing this from this branch :/
> needs more debugging ^^'

do you mean this error?
TypeError: "dbUser is undefined"
    subscribeToAuthStateChanged index.js:74

**Comment by waedi** [comment]
can someone check if this PR works also on your machine please? or if you want to review the code, is also a good thing

**Comment by waedi** [comment]
i ve added a new trick to centralise the colour definitions in this PR (as you can see in this commit https://github.com/psit4-lamas/PSIT4-LaMaS/pull/109/commits/303d97fd251a5f9b6c1b0cd337b579133682b0f2) so that when we will need to assign a colour on a component, but then decide that the dominant "pink" colour is too much  we just need to fix that in one place and every component will get that new colour

**Pull request merged**
