### PR TITLE
Feature/overview

### PR DESCRIPTION
**Pull request by tduong992**
This PR solves the following tickets:
- #129 Edit subject's overview
- #128 Show subject's overview

No tests coverage provided!

Needs review:
- German translation check
- manual UI test to check the workflow works as expected
  - test as TUTOR
  - test as STUDENT

### CODE REVIEW

**Comment by tduong992** [comment]
Still misses a couple of things I would like to add before merging...
But you can start with a first quick review, I ll come back to this PR as soon as I merge the other PRs

**Comment by wumacH** [comment]
i checked the functionality, it works as expected, in the german version the title of the "Uberblick" (in Menu left) should be with capitalized "Ü" -> "Überblick", the code changes are to large to check that now at the moment, but because from a user experience the functionality is there, it should be fine :-) thank you! so from my point of view just go a head and merge it when you think it is finished  👍 (but don't wait to long, i expect many merge conflicts with my "comments" branch afterwards)

**Comment by tduong992** [comment]
> i checked the functionality, it works as expected, in the german version the title of the "Uberblick" (in Menu left) should be with capitalized "Ü" -> "Überblick", the code changes are to large to check that now at the moment, but because from a user experience the functionality is there, it should be fine :-) thank you! so from my point of view just go a head and merge it when you think it is finished 👍 (but don't wait to long, i expect many merge conflicts with my "comments" branch afterwards)

yes, I tried to fix that "Ü" in the left menu, but couldn't find any solution ^^' actually in the ```public/locales/de/translation.json``` it is set with "Ü" but only for the menu it is not rendered with the umlaut :/ 

about the conflicts there will be a lot anyway also from publish feature xd don't worry, I ll fix them!

**Comment by tduong992** [comment]
Painful.. But finally this can be merged! whoop whoop 🎉 😄
After several troubles, such as:
- trying to get the proper/expected state/props when something has changed
- or a file is actually uploaded but it does not appear in the editor (person who edits) FileList table edit page
- or setting the lecture to be published from edit page
- ...
now all those "bugs" should be fixed...
And of course "Overview" feature is now also completed 😊 

Thanks @wumacH for the review and your help! :D

**Pull request merged**
